import type { NextPage } from "next";
import Head from "next/head";
import { BsEyeFill } from "react-icons/bs";
import { GiTargetPoster } from "react-icons/gi";
import Footer from "../components/layout/Footer";
import LogoBanner from "../components/layout/LogoBanner";
import NavBar from "../components/layout/NavBar";
import TopBanner from "../components/layout/TopBanner";
import NewsTicker from "../components/NewsTicker";


const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Govt Polytechnic College, Perinthalmanna</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <TopBanner />
      <LogoBanner />
      <NavBar />
      <NewsTicker />

      <div className="container my-3 mx-auto">
        <div className="flex flex-col lg:flex-row">
          <div className="w-full lg:w-3/4">
            <h1 className="text-2xl font-bold text-gray-700 my-3">
              Welcome to Govt Polytechnic College Perinthalmanna
            </h1>
            <div className="flex">
              <div
                className="w-2/4 2xl:w-2/5 min-h-full bg-cover bg-no-repeat bg-center relative"
                style={{
                  backgroundImage:
                    "url('https://www.gptcperinthalmanna.in/wp-content/uploads/2021/04/main1-scaled.jpg')",
                }}
              >
                <a className="absolute bottom-2 left-2 py-2 px-3 bg-gray-800 text-xs text-gray-50 hover:bg-gray-700 cursor-pointer transition-all duration-200">
                  Virtual Tour
                </a>
              </div>
              <div className="bg-gray-200 p-3 w-2/4 2xl:w-3/5 flex-grow">
                <h2 className="text-xl font-serif font-semibold">
                  About our College
                </h2>
                <p className="font-serif">
                  Govt Polytechnic College Perinthalmanna is one of the leading
                  institutions of its kind in Kerala. Academically and otherwise
                  its position in the state is unchallenged. Activities focusing
                  on the result enhancement and the overall development of the
                  students to make them excel in their respective fields are
                  remarkable. The college has a rich tradition to look back. The
                  present is praiseworthy, so the future has to be envisioned in
                  the light of the glorious past and the meritorious present
                </p>
                <div className="text-gray-500 text-sm pt-4 cursor-pointer hover:text-gray-600">
                  - Know More
                </div>
              </div>
            </div>
          </div>
          <div className="w-full flex flex-col h-60 lg:h-auto mt-3 lg:mt-0 lg:w-1/4 lg:pl-2">
            <h1 className="text-2xl font-bold text-gray-700 my-3">Events</h1>

            <div className="flex h-full">
              <div
                className="group cursor-pointer w-full min-h-full bg-cover bg-no-repeat bg-center relative"
                style={{
                  backgroundImage:
                    "url('http://uoce.chimpgroup.com/wp-content/uploads/Home-About-Us.jpg')",
                }}
              >
                <div className="absolute opacity-0 group-hover:opacity-100 transition-opacity duration-500 ease-in-out top-2 left-2 bg-gray-700 text-xs text-white rounded p-1">
                  {" "}
                  12 Oct 2021
                </div>
                <div className="absolute group-hover:pb-4 bottom-0 w-full opacity-90 py-2 px-3 bg-gray-800 text-xs text-gray-50 group-hover:bg-gray-700 cursor-pointer transition-all duration-200">
                  <h2 className="text-sm font-bold">Meet up 2021</h2>
                  <p className="font-serif">
                    Electronics 2014 batch is conducted a meetup in Electroncis
                    block
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div className="bg-cover container mx-auto bg-no-repeat  bg-bottom" style={{backgroundImage: "url('https://www.gptcperinthalmanna.in/wp-content/uploads/2021/04/main1-scaled.jpg')"}}>
  <div className="mx-auto lg:px-4 bg-gray-900 bg-opacity-80 flex justify-center">
    <div className="w-2/3 py-16 text-center">
      <div className="w-20 text-white mx-auto">
      <BsEyeFill size={70} />
      </div>
      <h1 className="text-2xl font-bold text-white"> Vision </h1>
      <p className="text-white text-sm"> To be a centre of excellence to mould technically competent engineers for industry expertise and social development. </p>
    </div>
    <div className="w-2/3 py-16 text-center">
      <div className="w-20 text-white mx-auto">
      
                <GiTargetPoster size={70} />
      </div>
      <h1 className="text-2xl font-bold text-white"> Mission </h1>
      <p className="text-white text-sm">Impart quality technical education and skills to develop engineering professionals to meet the needs of industry and society. 
        Facilitate professional interactions between industry and engineers and to promote innovation and entrepreneurship.
        Inculcate moral values and life ethics in engineering professionals to serve the society.</p>
    </div>
  </div>
</div>
<Footer />
    </div>
  );
};

export default Home;
